### ISSUE TITLE
Move IRC logic to using the IRC lib

### ISSUE THREAD

**Issue by benhoff** [benhoff/CHATIMUSMAXIMUS#1]
https://github.com/gawel/irc3

**Comment by dptechdev** [comment]
Are you currently working on this?

**Comment by benhoff** [comment]
yea, you can see my current progress in the 'dev' branch right now. Trying to get everything standardized on the asynico library.

**Comment by benhoff** [comment]
Finished. 3982ca06f81cf2c3f0de42cdad4186d04b42841d
